version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run: sudo pip install --upgrade pip setuptools
  unittest:
    steps:
      - setup
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: hash -r  # for pytest ?
      - run: pytest ./test/python

jobs:
  unittest:
    docker:
      - image: circleci/python:3.10
    steps:
      - unittest

workflows:
  main:
    jobs:
      - unittest
