version: 2.1

commands:
  install-trivy:
    steps:
      - run: curl -fSsLo trivy.deb https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb && sudo dpkg -i trivy.deb && rm trivy.deb
  python_test:
    steps:
      - checkout
      - run: sudo pip install --upgrade pip setuptools
      - run: pip install . -r requirements-dev.txt
      - run: ./pp pytest ./test/python
  node_test:
    steps:
      - checkout
      - run: npm install
      - run: JEST_JUNIT_OUTPUT=junit-results/jest/junit.xml ./node_modules/jest/bin/jest.js --reporters=default --reporters=jest-junit --runInBand --ci

jobs:
  python_test:
    docker:
      - image: circleci/python:3.10
    steps:
      - python_test
  node_test:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - node_test
  trivy-scan-project:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - install-trivy
      - run: mkdir -p artifacts/trivy && trivy fs . --debug
      - store_artifacts:
          path: artifacts/trivy/

workflows:
  main:
    jobs:
      - node_test
      - python_test
      - trivy-scan-project
