name: pre-commit
permissions: read-all
run-name: Pre commit checks for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: pip install pre-commit
      - run: pre-commit run eslint --all-files
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo pip install --upgrade pip setuptools
      - run: pip install . -r requirements-dev.txt
      - run: pre-commit run pylint --all-files
